# Generated by Django 5.2.3 on 2025-07-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainstate',
            name='active_nodes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blockchainstate',
            name='last_block_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blockchainstate',
            name='total_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blockchainstate',
            name='last_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_state', to='image_app.block'),
        ),
    ]
