# Generated by Django 5.2.3 on 2025-07-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_blockchainstate_active_nodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.PositiveIntegerField(db_index=True)),
                ('block_hash', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entry', to='image_app.block')),
            ],
            options={
                'ordering': ['block_index'],
            },
        ),
        migrations.AddField(
            model_name='blockchainstate',
            name='ledger_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_chain', to='image_app.ledger'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['block_index', 'block_hash'], name='image_app_l_block_i_4ff4a7_idx'),
        ),
    ]
